//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace S2T4Bank.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class BotLanguage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BotLanguage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("S2T4Bank.Resources.BotLanguage", typeof(BotLanguage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conversation annulée. Vous êtes de retour au point de départ..
        /// </summary>
        public static string CancelCancel {
            get {
                return ResourceManager.GetString("CancelCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ceci est l&apos;aide. Tapez &apos;annuler&apos; ou &apos;stop&apos; pour arrêter la conversation..
        /// </summary>
        public static string CancelHelp {
            get {
                return ResourceManager.GetString("CancelHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quelle durée pour l&apos;emprunt ?.
        /// </summary>
        public static string LoanDurationStep {
            get {
                return ResourceManager.GetString("LoanDurationStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quelle type d&apos;assurance ?.
        /// </summary>
        public static string LoanInsuranceStep {
            get {
                return ResourceManager.GetString("LoanInsuranceStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quel montant voulez-vous emprunter ?.
        /// </summary>
        public static string LoanLoanStep {
            get {
                return ResourceManager.GetString("LoanLoanStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Je n&apos;ai pas compris, je suis désolé. Pouvez-vous réessayer ?.
        /// </summary>
        public static string LoanNotUnderstood {
            get {
                return ResourceManager.GetString("LoanNotUnderstood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emprunt :
        ///- Montant : {0} {1}
        ///- Durée : {2}
        ///- Assurance : {3}.
        /// </summary>
        public static string MainFinalStep {
            get {
                return ResourceManager.GetString("MainFinalStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merci, ce sera pour une prochaine fois..
        /// </summary>
        public static string MainFinalStepThanks {
            get {
                return ResourceManager.GetString("MainFinalStepThanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Que puis-je faire pour vous aujourd&apos;hui?
        ///Dites par exemple : &apos;Je veux emprunter 10000 euros sur une période de 3 ans&apos;.
        /// </summary>
        public static string MainIntroStep {
            get {
                return ResourceManager.GetString("MainIntroStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entrez l&apos;information de culture que vous souhaitez. Par exemple &apos;en-US&apos; ou &apos;fr-FR&apos;.
        /// </summary>
        public static string MainLanguage {
            get {
                return ResourceManager.GetString("MainLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOTE: LUIS n&apos;est pas configuré. Pour pouvoir utiliser toutes les capacités de ce bot, ajoutez &apos;LuisAppId&apos;, &apos;LuisAPIKey&apos; et &apos;LuisAPIHostName&apos; dans le fichier appsettings.json..
        /// </summary>
        public static string MainLuisError {
            get {
                return ResourceManager.GetString("MainLuisError", resourceCulture);
            }
        }
    }
}
